# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gptformats-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/saniygit/azure-open-ai-embeddings-qna/
        username: ${{ secrets.AzureAppService_ContainerUsername_d0cab61c4f1344b2b979543de1dabd3c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c0a503d93c9f48a3aef0afa2eee327c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/saniygit/azure-open-ai-embeddings-qna/${{ secrets.AzureAppService_ContainerUsername_d0cab61c4f1344b2b979543de1dabd3c }}/fruocco/oai-embeddings:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gptformats-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5143e9743a2843ff98359303df871ef2 }}
        images: 'github.com/saniygit/azure-open-ai-embeddings-qna/${{ secrets.AzureAppService_ContainerUsername_d0cab61c4f1344b2b979543de1dabd3c }}/fruocco/oai-embeddings:${{ github.sha }}'